### ISSUE TITLE
Ping to stay connected

### ISSUE THREAD

**Issue by noobermin** [lwfinger/rtl8723au#55]
So, I realized that I need to often disconnect and reconnect my laptop (yoga 13)  to my router at home, this sometimes happens for other routers too. However, strangely enough, I've found that if I keep an active ping running (like pinging some random server like google), the connection does not stop.

I will provide any other information you need. I currently have linux 3.18.0 and use the staging driver for that version.

**Comment by budb** [comment]
Funny, I did the same thing. The issue persist in 3.18.2-2. Other devices on the same network work. Also there is a huge ping deviation --> 34 / 82 / 332 /(min/avg/max).

**Comment by noobermin** [comment]
If it is relevant, my router is a netgear CG3000D model.

**Comment by lwfinger** [comment]
If you are running the in-kernel version of the driver, there is a better place to report problems. This repo is only provided for those people whose kernel does not have the driver.

You can get the program authors from a 'modinfo r8723au' command. Jes Sorensen is the maintainer. Send such comments to him with a Cc to linux-wireless@vger.kernel.org.

As a workaround, try loading the module with "rtw_ips_mode=2". That is supposed to enable a firmware keep-alive. If that does not work, try "rtw_ips_mode=0". The default value is 1.

If you need to keep a ping running, it would be better to ping your router rather than some external host such as Google.
